server:
  port: 8085
  servlet:
    context-path: /test1
spring:
  application:
    name: test2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.51:3306/test_0
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
# liteflow 配置
liteflow:
  # 规则文件路径配置
  rule-source: config/flow.xml
  #全局异步节点线程池大小，默认为64
  global-thread-pool-size: 100
  #全局异步节点线程池队列大小，默认为512
  global-thread-pool-queue-size: 512