gate:
  ignore:
    authentication:
      startWith: /oauth
  token:
    salt: token

knife4j:
  enable: true

jetcache:
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      poolConfig:
        minIdle: 1
        maxIdle: 2
        maxTotal: 3
      host: ${spring.redis.host:192.168.1.2}
      port: ${spring.redis.port:6379}
  local:
    default:
      type: linkedhashmap


# Redis服务器连接端口
spring:
  redis:
    port: 6379
  # Redis服务器地址
    host: 192.168.1.2
  # Redis数据库索引（默认为0）
    database: 0
    # 连接超时时间（毫秒）
    timeout: 5000ms
  # Redis服务器连接密码（默认为空）
#    password
  # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 8
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  # 连接池中的最大空闲连接
        max-idle: 8
  # 连接池中的最小空闲连接
        min-idle: 0