gate:
  token:
    salt: token

knife4j:
  enable: true

jetcache:
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      poolConfig:
        minIdle: 1
        maxIdle: 2
        maxTotal: 3
      host: 192.168.3.51
      port: 6379
  local:
    default:
      type: linkedhashmap
spring:
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.3.51:3306/test_0
        username: root
        password: 123456
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.3.51:3306/test_1
        username: root
        password: 123456
    sharding:
      tables:
        project:
          actual-data-nodes: ds$->{0..1}.project_$->{0..1}
          key-generator:
            column: id
            type: SNOWFLAKE
            props:
              max.vibration.offset: 4
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: project_$->{id % 2}
          database-strategy:
            standard:
              sharding-column: id
              precise-algorithm-class-name: com.learning.temp.strategy.TableShardingAlgorithm
    props:
      sql:
        show: true